# Risk Management Configuration for CryptoTradeBotGlobal
# Enterprise-grade risk controls and financial safety measures

# =============================================================================
# PORTFOLIO RISK MANAGEMENT
# =============================================================================
portfolio_risk:
  # Overall Portfolio Limits
  max_portfolio_risk: 0.10          # 10% of total portfolio at risk
  max_daily_loss: 0.05               # 5% maximum daily loss
  max_weekly_loss: 0.15              # 15% maximum weekly loss
  max_monthly_loss: 0.25             # 25% maximum monthly loss
  max_drawdown: 0.20                 # 20% maximum drawdown
  
  # Position Sizing
  default_position_size: 0.02        # 2% of portfolio per position
  max_position_size: 0.05            # 5% maximum single position
  max_correlation_exposure: 0.15     # 15% max exposure to correlated assets
  
  # Diversification Rules
  max_positions_per_asset: 1
  max_positions_per_strategy: 5
  max_total_positions: 10
  min_portfolio_diversification: 5   # Minimum 5 different assets
  
  # Concentration Limits
  max_single_asset_exposure: 0.20    # 20% max exposure to single asset
  max_exchange_exposure: 0.60        # 60% max exposure to single exchange
  max_strategy_exposure: 0.40        # 40% max exposure to single strategy

# =============================================================================
# POSITION RISK MANAGEMENT
# =============================================================================
position_risk:
  # Stop Loss Configuration
  default_stop_loss: 0.03            # 3% default stop loss
  max_stop_loss: 0.08                # 8% maximum stop loss
  trailing_stop_activation: 0.02     # Activate trailing stop at 2% profit
  trailing_stop_distance: 0.015      # 1.5% trailing stop distance
  
  # Take Profit Configuration
  default_take_profit: 0.06          # 6% default take profit
  partial_profit_levels:
    - level: 0.03                    # Take 25% profit at 3%
      percentage: 0.25
    - level: 0.05                    # Take 25% profit at 5%
      percentage: 0.25
    - level: 0.08                    # Take 50% profit at 8%
      percentage: 0.50
  
  # Position Sizing Methods
  position_sizing:
    default_method: "fixed_percentage"
    methods:
      fixed_percentage:
        percentage: 0.02             # 2% of portfolio
      volatility_adjusted:
        target_volatility: 0.15      # 15% target volatility
        lookback_period: 20          # 20 periods for volatility calculation
      kelly_criterion:
        win_rate: 0.55               # Historical win rate
        avg_win: 0.04                # Average win percentage
        avg_loss: 0.02               # Average loss percentage
        kelly_fraction: 0.25         # Use 25% of Kelly recommendation
      
  # Order Management
  order_management:
    max_order_size: 5000.0           # Maximum single order size
    min_order_size: 10.0             # Minimum order size
    order_split_threshold: 2000.0    # Split orders larger than this
    max_slippage: 0.005              # 0.5% maximum slippage
    order_timeout: 300               # 5 minutes order timeout

# =============================================================================
# MARKET RISK CONTROLS
# =============================================================================
market_risk:
  # Volatility Controls
  volatility_limits:
    max_portfolio_volatility: 0.25   # 25% maximum portfolio volatility
    volatility_lookback: 30          # 30 periods for volatility calculation
    high_volatility_threshold: 0.40  # Reduce positions above 40% volatility
    volatility_adjustment_factor: 0.5 # Reduce position size by 50% in high vol
  
  # Market Regime Detection
  market_regimes:
    enable_regime_detection: true
    regimes:
      bull_market:
        condition: "trend_up"
        max_leverage: 1.0
        position_size_multiplier: 1.0
      bear_market:
        condition: "trend_down"
        max_leverage: 0.5
        position_size_multiplier: 0.7
      sideways_market:
        condition: "trend_sideways"
        max_leverage: 0.8
        position_size_multiplier: 0.9
      high_volatility:
        condition: "volatility_high"
        max_leverage: 0.3
        position_size_multiplier: 0.5
  
  # Correlation Risk
  correlation_risk:
    max_correlation: 0.7             # Maximum correlation between positions
    correlation_lookback: 60         # 60 periods for correlation calculation
    correlation_adjustment: true     # Adjust position sizes based on correlation
    
  # Liquidity Risk
  liquidity_risk:
    min_daily_volume: 1000000        # Minimum $1M daily volume
    max_market_impact: 0.002         # 0.2% maximum market impact
    liquidity_buffer: 0.1            # 10% liquidity buffer

# =============================================================================
# OPERATIONAL RISK CONTROLS
# =============================================================================
operational_risk:
  # System Limits
  system_limits:
    max_orders_per_second: 5
    max_orders_per_minute: 100
    max_orders_per_hour: 1000
    max_api_calls_per_minute: 500
    
  # Connection Risk
  connection_risk:
    max_connection_failures: 3       # Max failures before circuit breaker
    circuit_breaker_duration: 300    # 5 minutes circuit breaker
    backup_exchange_activation: true # Activate backup exchange on failure
    
  # Data Quality Controls
  data_quality:
    price_deviation_threshold: 0.05  # 5% price deviation alert
    volume_anomaly_threshold: 5.0    # 5x volume anomaly alert
    missing_data_tolerance: 0.02     # 2% missing data tolerance
    stale_data_threshold: 300        # 5 minutes stale data threshold
    
  # Error Handling
  error_handling:
    max_consecutive_errors: 5
    error_cooldown_period: 600       # 10 minutes cooldown
    auto_disable_on_errors: true
    manual_override_required: true

# =============================================================================
# REGULATORY AND COMPLIANCE
# =============================================================================
compliance:
  # Trading Limits
  trading_limits:
    max_daily_trades: 1000
    max_weekly_trades: 5000
    max_monthly_volume: 10000000     # $10M monthly volume limit
    
  # Reporting Requirements
  reporting:
    trade_reporting: true
    position_reporting: true
    risk_reporting: true
    compliance_reporting: true
    
  # Audit Trail
  audit_trail:
    log_all_trades: true
    log_risk_decisions: true
    log_system_events: true
    retention_period: 2555           # 7 years in days
    
  # KYC/AML Compliance
  kyc_aml:
    enable_kyc_checks: false         # Disabled for crypto trading
    enable_aml_monitoring: true
    suspicious_activity_threshold: 100000  # $100K threshold
    
# =============================================================================
# RISK MONITORING AND ALERTS
# =============================================================================
monitoring:
  # Real-time Monitoring
  real_time:
    enable_real_time_monitoring: true
    monitoring_interval: 30          # 30 seconds
    alert_latency_threshold: 5       # 5 seconds max alert latency
    
  # Risk Metrics Calculation
  risk_metrics:
    calculate_var: true              # Value at Risk
    var_confidence_level: 0.95       # 95% confidence level
    var_time_horizon: 1              # 1 day time horizon
    calculate_cvar: true             # Conditional Value at Risk
    calculate_sharpe: true           # Sharpe ratio
    calculate_sortino: true          # Sortino ratio
    calculate_max_drawdown: true     # Maximum drawdown
    
  # Alert Configuration
  alerts:
    # Portfolio Level Alerts
    portfolio_alerts:
      drawdown_alert: 0.10           # Alert at 10% drawdown
      daily_loss_alert: 0.03        # Alert at 3% daily loss
      position_limit_alert: 0.90    # Alert at 90% of position limit
      
    # Position Level Alerts
    position_alerts:
      stop_loss_hit: true
      take_profit_hit: true
      position_size_exceeded: true
      correlation_exceeded: true
      
    # System Level Alerts
    system_alerts:
      connection_failure: true
      data_quality_issue: true
      order_execution_failure: true
      api_rate_limit_hit: true
      
    # Alert Channels
    alert_channels:
      email: true
      slack: true
      telegram: true
      webhook: true
      sms: false                     # Disabled by default

# =============================================================================
# EMERGENCY PROCEDURES
# =============================================================================
emergency:
  # Circuit Breakers
  circuit_breakers:
    portfolio_loss_breaker:
      threshold: 0.15                # 15% portfolio loss
      action: "stop_all_trading"
      duration: 3600                 # 1 hour
      
    volatility_breaker:
      threshold: 0.50                # 50% volatility
      action: "reduce_positions"
      reduction_factor: 0.5          # Reduce by 50%
      
    system_error_breaker:
      threshold: 10                  # 10 consecutive errors
      action: "emergency_shutdown"
      manual_restart_required: true
      
  # Emergency Actions
  emergency_actions:
    emergency_shutdown:
      close_all_positions: true
      cancel_all_orders: true
      disable_new_trades: true
      send_emergency_alerts: true
      
    position_reduction:
      reduce_by_percentage: 0.5      # Reduce all positions by 50%
      prioritize_losing_positions: true
      maintain_stop_losses: true
      
    safe_mode:
      paper_trading_only: true
      reduced_position_sizes: true
      increased_monitoring: true
      manual_approval_required: true
      
  # Recovery Procedures
  recovery:
    auto_recovery: false             # Manual recovery required
    recovery_checklist:
      - "Review system logs"
      - "Analyze risk metrics"
      - "Check market conditions"
      - "Verify system integrity"
      - "Test with small positions"
      - "Gradual position increase"
    
    recovery_criteria:
      max_drawdown_recovered: 0.05   # Drawdown below 5%
      system_stability_confirmed: true
      market_conditions_favorable: true
      manual_approval_obtained: true

# =============================================================================
# BACKTESTING RISK PARAMETERS
# =============================================================================
backtesting:
  # Risk Assumptions
  risk_assumptions:
    transaction_costs: 0.001         # 0.1% transaction costs
    slippage_assumption: 0.0005      # 0.05% slippage
    funding_costs: 0.0001            # 0.01% daily funding costs
    
  # Stress Testing
  stress_testing:
    enable_stress_tests: true
    stress_scenarios:
      market_crash:
        price_drop: 0.50             # 50% price drop
        duration: 7                  # 7 days
      flash_crash:
        price_drop: 0.20             # 20% price drop
        duration: 1                  # 1 day
      high_volatility:
        volatility_increase: 3.0     # 3x normal volatility
        duration: 30                 # 30 days
      liquidity_crisis:
        volume_reduction: 0.5        # 50% volume reduction
        spread_increase: 5.0         # 5x normal spreads
        
  # Monte Carlo Simulation
  monte_carlo:
    enable_monte_carlo: true
    simulation_runs: 10000
    confidence_intervals: [0.95, 0.99]
    random_seed: 42
