name: CI e Deploy via SSH

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r CryptoTradeBotGlobal/requirements.txt

      - name: Rodar testes
        run: |
          cd CryptoTradeBotGlobal
          pytest --maxfail=1 --disable-warnings -v

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd /caminho/do/seu/projeto
            git pull
            docker-compose up -d --build

      - name: Upload para AWS S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'CryptoTradeBotGlobal/'

      # Exemplo de passo para subir arquivos para nuvem (ajuste conforme provedor)
      # - name: Upload para nuvem
      #   run: |
      #     scp -i ${{ secrets.DEPLOY_KEY }} arquivo.txt usuario@host:/destino
